name: "Create a formally tagged release upon creating a targeted pull request to 'main' branch"
on:
 pull_request:
  branches:
   - main
jobs:
    validate-tags:
        environment: RELEASE
        runs-on: ubuntu-latest
    
        steps:
            - name: Create release
              uses: heyitsDani/reusable-workflows/.github/actions/release_semantic_tag@feat/releases
              with:
                    PAT_TOKEN: ${{ secrets.GIT_PAT}}
                    REPO_URL: ${{ github.repositoryUrl}}
                    PR_SHA: ${{github.event.pull_request.head.sha}}
