name: "Create a formally tagged release upon creating a targeted pull request to 'main' branch"
run-name: "${{github.event.inputs.Environment}}; ${{ github.ref}}; ${{github.triggering_actor}};"

on:
 workflow_dispatch:
    inputs:
      Environment:
        type: choice
        description: "Select Deployment Environment"
        options:
        - PROD
        - UAT
        - SIT
        - DEV
      
permissions:
  contents: write
        
jobs:
    validate-tags:    
        uses: heyitsDani/reusable-workflows/.github/workflows/release_semantic_tag.yaml@main # switch to semantically versioned releases
        with:
          REPO_URL: ${{ github.repositoryUrl}}
          PR_SHA: ${{github.sha}}
        secrets:
           PAT_TOKEN: ${{ secrets.GIT_PAT}}
