name: "Create a formally tagged release upon creating a targeted pull request to 'main' branch"
run-name: "${{github.event.inputs.Environment}}; ${{ github.ref}}; ${{github.triggering_actor}};"

on:
 workflow_dispatch:
    inputs:
      Environment:
        type: choice
        description: "Select Deployment Environment"
        options:
        - PROD
        - UAT
        - SIT
        - DEV
        
jobs:
    validate-tags:
        environment: RELEASE
        runs-on: ubuntu-latest
    
        steps:
            - name: Create release
              uses: heyitsDani/reusable-workflows/.github/actions/release_semantic_tag@feat/releases
              with:
                    PAT_TOKEN: ${{ secrets.GIT_PAT}}
                    REPO_URL: ${{ github.repositoryUrl}}
                    PR_SHA: ${{github.sha}}
